### ISSUE TITLE
False Yahoo Results

### ISSUE THREAD

**Issue by marlowmedia** [sdwolfe32/trumail#13]
Hey,

Gmail/Outlook/Hotmail/Aim seem to work fine but for Yahoo it seems to give false reports like the below:

`{
    "address": "dsgdfh23.sdfg@yahoo.com",
    "username": "dsgdfh23.sdfg",
    "domain": "yahoo.com",
    "hostExists": true,
    "deliverable": true,
    "fullInbox": false,
    "catchAll": true,
    "disposable": false,
    "gravatar": false
}`

That email address is not valid but your script is showing it as valid?

**Comment by marlowmedia** [comment]
I've actually just been reading Closed issues and i came across this that you said:

> The reason for this is because the first thing that we check is whether or not the domain has a catch-all. In other words, We first verify the existence of a randomly generated email address - for example d23f9hasdf2f@yahoo.com. If that exists, all addresses on that domain will definitely be deliverable and we avoid doing a per address check. Since yahoo is a widely known catch-all domain and returns deliverable: true for all addresses (that I've ever tried) we assume it's deliverable and return true. I'll do some playing with invalid-length addresses and see if it's worth removing the assumption that all addresses will be deliverable given a catch-all domain.

I dont really get why you would mark an email as Valid when clearly its not, it basically means that no matter what yahoo email address is used it will always show as Valid meaning theres not much point in running Yahoo email address through your script if there all going to come back saying Valid?

**Comment by sdwolfe32** [comment]
Yahoo is currently a catch-all - therefore all addresses are deliverable. We check every time just in case something changes on Yahoos end. Who knows? - they may return something other than a 200 some day.

How do you suggest I verify TRUE deliverability of an email when yahoo will give me a 200 for everything I give it?

I have no access to their database so I cannot tell you for sure whether there's a person behind an address or not. This service aims to do exactly that, however there are some domains where it's just not possible.

Also I do not mark anything as valid or not. I provide you as much information as I can in the output. I mark catch-alls as "deliverable" because the are truly "deliverable". They are also catch-all and this is something you should be considering in your application since there is a chance the address is completely made up. If "catch-all" is false and "deliverable" is true - there is a much better chance that the address is legit.

**Comment by dare05** [comment]
Well there must be a way since services like ZeroBounce successfully make a distinction between a valid and invalid Yahoo address.

**Comment by sdwolfe32** [comment]
That link is very interesting... I think this is something we can get implemented.

**Comment by marlowmedia** [comment]
Interesting code, if I'm reading the code correctly it's using the registration pages to see if a user is valid or not. If the user is already taken then it's valid. If not then it's not valid.

Very smart way of doing it and that way it means you bypass the IP Reputation right?

**Comment by twisted1919** [comment]
@sdwolfe32 / @dare05 / @marlowmedia - Checking the email using the registration api is not okay to do because you are allowed to only issue a few queries before you are blocked for 24 hours, so when doing a bulk action, to check 1000 emails, there's no way for this to properly work.

**Comment by dare05** [comment]
@twisted1919 of course (you can use proxies to avoid this), but you said it's "not okay", do you know anything better?

**Comment by sdwolfe32** [comment]
I'm going to do some messing around with these over the weekend. If there's truely a block then put on ips that perform too many requests I won't bother implementing it, otherwise why not?
