### ISSUE TITLE
Email provider support

### ISSUE THREAD

**Issue by zyadsherif** [sdwolfe32/trumail#2]
Hey I wanted to know if you are focusing on specific providers because currently a lot of the german email providers aren't working with your API, for ex. (GMX, Web.de, 1&1)

I think they have different responses and behaviours than the standard (Gmail, G-suite, Yahoo, iCloud)

Do you intend to support those as well in the future?

Thanks ;)

**Comment by sdwolfe32** [comment]
Thank you for bringing this up. I remember running into this issue when I was building the app a few months ago. The issue is that the server needs to have a PTR record that identifies the hostname using the hosts IP. Since Heroku doesn't natively support this type of thing I'll need to find an addon that does or host it elsewhere.

I'll work on taking care of this!

Thank you for the feedback, this should be a fairly simple fix!
