### ISSUE TITLE
nolisting / multiple mx

### ISSUE THREAD

**Issue by zxfrank** [sdwolfe32/trumail#26]
I tested with gmail, works great.

When the target has multiple MX and the 1st timeout (nolisting), there's no fallback and the result is timeout

**Comment by sdwolfe32** [comment]
Hmm, this is awesome info. I've noticed a large number of timeouts however I assumed it was due to slow servers. I never considered checking the other mx servers. I'll definitely be debugging this tonight and let you know what I find. Thanks so much!

**Comment by sdwolfe32** [comment]
I've updated the verifier https://github.com/sdwolfe32/trumail/commit/834eeccefeb8e7fdd080c4634faf0af5d4f94139 to attempt a connection to all MX servers simultaneously (since we need to respond within 30 seconds) - using the first valid connection established. I'm hoping this helps however if you continue to see timeouts it is likely a limitation of herokus 30 second timeout

**Comment by zxfrank** [comment]
You
Are
A
Genius!!

**Comment by sdwolfe32** [comment]
I've done my best to re-add the no-listing concurrent connection stuff. As far as I know the go-routine leak should be fixed. If not I'll take care of it without removing the concurrent server connection stuff
