### ISSUE TITLE
Minimum Length E-Mail

### ISSUE THREAD

**Issue by nerdbaggy** [sdwolfe32/trumail#3]
Love what you are doing,
One idea I have is setting the minimum length for an email to be valid.
For example checking a@yahoo.com returns that its valid, even though its too short to be an actual yahoo email address. I can work on figuring out the numbers if needed

**Comment by sdwolfe32** [comment]
The reason for this is because the first thing that we check is whether or not the domain has a catch-all. In other words, We first verify the existence of a randomly generated email address - for example `d23f9hasdf2f@yahoo.com`. If that exists, all addresses on that domain will definitely be deliverable and we avoid doing a per address check. 

Since yahoo is a widely known catch-all domain and returns `deliverable: true` for all addresses (that I've ever tried) we assume it's deliverable and return true. I'll do some playing with invalid-length addresses and see if it's worth removing the assumption that all addresses will be deliverable given a catch-all domain.

Thanks for the feedback! I'll get back to you soon.

**Comment by sdwolfe32** [comment]
I've done some testing and by the way it looks, Yahoos MX servers respond with a 250 for `a@yahoo.com`. So while they may not allow a user to have an address with 1 username character, the address `a@yahoo.com` is still considered a valid email (according to yahoo's MX server). As of right now I don't see any benefit in removing the assumption that catch-all domains will result in full deliverability. I'm going to close this issue since catch-all providers, for the most part, don't always apply the same validation logic to their mail exchanger and account management.
