### ISSUE TITLE
Add X-RateLimit-* headers to 429 responses

### ISSUE THREAD

**Issue by pmatseykanets** [sdwolfe32/trumail#41]
I'd suggest considering adding X-RateLimit-* headers to 429 responses to help automatically taking corrective measures and stopping hammering the API unnecessarily.

Of course there are different ways to go about it. I.e. 

- X-RateLimit-Limit - Request limit per time window
- X-RateLimit-Remaining - The number of requests left for the time window window
- X-RateLimit-Reset - The remaining window before the rate limit resets in UTC epoch seconds

Thanks for consideration and a great service!

**Comment by sdwolfe32** [comment]
I read about this recently and the thought crossed my mind. Since then I've completely forgotten. Thanks for reminding me I'll do my best to take care of adding that tonight!

**Comment by sdwolfe32** [comment]
Again thanks for the suggestion! I've taken care of implementing it on the public API!

Note: You may notice the rate limit acting slightly inconsistent on the public endpoints since we have multiple instances running and are only storing the data in a local map. I'll be adding Redis to account for this soon it's just not as high on my priority list.

**Comment by pmatseykanets** [comment]
Thank you so much for such a quick turnaround. I'll take for a spin soon.

And of course Redis or any other centralized storage is essential to properly keep track of limits. Hopefully you'll be able to add it soon.

Thanks again.
