### ISSUE TITLE
serverless?

### ISSUE THREAD

**Issue by mhussa** [sdwolfe32/trumail#8]
Have you considered using your client lib in an AWS lambda function?  Using something like Apex to upload the Go function and your verifier lib?   Maybe use SNS to send the deliverability email?

Just wondering if you've thought about it as a possible deployment option.

Thankyou for creating this and sharing it :+1:

**Comment by sdwolfe32** [comment]
Since the biggest issue I have lately is being IP blacklisted by email providers, you bet I’ve considered AWS Lambda (I’m assuming each time a lambda is spun up a random machine/up is used). Once I iron out some other issues and have the verifier more stable I definitely would like to move it to Lambda. I’ll do some more research soon!

**Comment by marlowmedia** [comment]
When/If you do do this then please offer a Tutorial on how to set this up as this would benefit alot of people :)

**Comment by paul-crashley** [comment]
I don't think Lambda would solve your issue. From the website:

> AWS Lambda tries to reuse the container for subsequent invocations of the Lambda function.

You would probably have to spin up a new Lambda function randomly, and apparently, it's a manual process.

Also, I'm wondering how valuable the deliverability check is if sometimes it may erroneously return false. If there's only a chance it might work, then there is no point in the check.

**Comment by sdwolfe32** [comment]
Yeah, I was thinking the same thing. If we went to lambda and my assumption is partially correct that we'll be using more IP addresses as senders, there's a higher chance - I feel - that we'll use a blacklisted IP. On a single heroku node we could be blacklisted all day/whitelisted all day, however if we use lambda and we're jumping from IP to IP I'd say probably 1/5 of the machines that run the lambdas will already be blacklisted (making 1 out of 5 verifications a blocked response).

**Comment by sdwolfe32** [comment]
Also, I personally have yet to be given a case where the deliverability check returns false erroneously. I cannot debug and fix if I have no examples. I have seen us get blocked by mail servers before (which returns deliverable:false) but that's always clearly stated in the output errors.

**Comment by paul-crashley** [comment]
Sorry, my erroneous comment probably isn't clear.

What I meant was, I can't think of any cases where a vague deliverability would be useful. For example, if I have a mailing list I'm trying to trim down to keep healthy, I would want a yes/no answer, not a maybe.

Once you introduce the fact that there is a possibility that the answer to your deliverability question isn't 100% correct, then it's never correct and useless.

**Comment by sdwolfe32** [comment]
Just to be clear we never return a maybe in any form. We return `deliverable:true` or `deliverable:false` or basically an`deliverable:false` (default) because there's an error.

Deliverable does not mean valid, it means deliverable. If you're cleaning out a mailing list for the soul purpose of preventing hard bounces, you can confidently use the deliverability flag because it's already yes/no (true/false) as it is - except for when there is an error (where it defaults to false and the error is provided).

You should be dealing with errors accordingly in your application in order to decide on your own whether the response is useful to you.
